import { integer, numeric, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { adminUsers } from './admin_users.js';
import { interventions } from './interventions.js';
import { stores } from './stores.js';

/**
 * Stores intervention recommendations generated by the Decision Engine.
 *
 * Lifecycle: pending → (approved | rejected | expired) → executed
 *
 * The Decision Engine writes a row here on every qualifying event.
 * Phase 2 execution only runs after an approval event (either admin-triggered
 * or auto-executed based on the store's intervention_approval_mode policy).
 * When executed, `intervention_id` is set to link this row to the actual
 * `interventions` row written by InterventionWriter.
 */
export const interventionRecommendations = pgTable('intervention_recommendations', {
  id: uuid('id').primaryKey().defaultRandom(),
  storeId: integer('store_id')
    .notNull()
    .references(() => stores.id),
  sessionId: text('session_id').notNull(),
  distinctId: text('distinct_id').notNull(),
  customerId: integer('customer_id'),
  /** Current risk score (0–1) computed by Phase 1 risk scorer. */
  riskScore: numeric('risk_score').notNull(),
  /** Future abandonment probability (0–1) from prediction model; null when model not loaded. */
  predictionProbability: numeric('prediction_probability'),
  /** Model confidence for prediction_probability; null when model not loaded. */
  predictionConfidence: numeric('prediction_confidence'),
  type: text('type').notNull(),
  channel: text('channel').notNull(),
  value: numeric('value'),
  /** pending | approved | rejected | executed | expired */
  status: text('status').notNull().default('pending'),
  approvedBy: integer('approved_by').references(() => adminUsers.id),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  rejectedBy: integer('rejected_by').references(() => adminUsers.id),
  rejectedAt: timestamp('rejected_at', { withTimezone: true }),
  executedAt: timestamp('executed_at', { withTimezone: true }),
  /** created_at + approvalTimeoutSeconds; recommendation becomes expired when now > expiresAt. */
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  /** Set when status = executed; links to the interventions row written by InterventionWriter. */
  interventionId: uuid('intervention_id').references(() => interventions.interventionId),
  triggerReason: text('trigger_reason'),
  featureSchemaVersion: text('feature_schema_version'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export type InterventionRecommendation = typeof interventionRecommendations.$inferSelect;
export type NewInterventionRecommendation = typeof interventionRecommendations.$inferInsert;
